export const creditCards = [
  { value: 'hdfc_infinia', label: 'HDFC Infinia Credit Card' },
  { value: 'hdfc_diners_black', label: 'HDFC Diners Club Black Credit Card' },
  { value: 'hdfc_regalia', label: 'HDFC Regalia Credit Card' },
  { value: 'hdfc_millennia', label: 'HDFC Millennia Credit Card' },
  { value: 'hdfc_moneyback', label: 'HDFC MoneyBack Credit Card' },
  { value: 'icici_amazon', label: 'ICICI Amazon Pay Credit Card' },
  { value: 'icici_coral', label: 'ICICI Coral Credit Card' },
  { value: 'icici_platinum', label: 'ICICI Platinum Chip Credit Card' },
  { value: 'icici_sapphiro', label: 'ICICI Sapphiro Credit Card' },
  { value: 'icici_emeralde', label: 'ICICI Emeralde Credit Card' },
  { value: 'axis_neo', label: 'Axis Bank Neo Credit Card' },
  { value: 'axis_ace', label: 'Axis Bank Ace Credit Card' },
  { value: 'axis_flipkart', label: 'Axis Bank Flipkart Credit Card' },
  { value: 'axis_magnus', label: 'Axis Bank Magnus Credit Card' },
  { value: 'axis_myzone', label: 'Axis Bank My Zone Credit Card' },
  { value: 'axis_atlas', label: 'Axis Bank Atlas' },
  { value: 'sbi_elite', label: 'SBI Card ELITE' },
  { value: 'sbi_simplyclick', label: 'SBI SimplyCLICK Credit Card' },
  { value: 'sbi_simplysave', label: 'SBI SimplySAVE Credit Card' },
  { value: 'sbi_prime', label: 'SBI Prime Credit Card' },
  { value: 'sbi_aurum', label: 'SBI Aurum Credit Card' },
  { value: 'amex_platinum', label: 'American Express Platinum Card' },
  { value: 'amex_gold', label: 'American Express Gold Card' },
  { value: 'amex_rewards', label: 'American Express Membership Rewards Credit Card' },
  { value: 'amex_platinum_reserve', label: 'American Express Platinum Reserve Credit Card' },
  { value: 'yes_prosperity', label: 'YES Prosperity Rewards Plus Credit Card' },
  { value: 'sc_ultimate', label: 'Standard Chartered Ultimate Credit Card' },
  { value: 'sc_manhattan', label: 'Standard Chartered Manhattan Platinum Credit Card' },
  { value: 'sc_platinum', label: 'Standard Chartered Platinum Rewards Credit Card' },
  { value: 'citi_premiermiles', label: 'Citi PremierMiles Credit Card' },
  { value: 'citi_cashback', label: 'Citi Cashback Credit Card' },
  { value: 'citi_rewards', label: 'Citi Rewards Credit Card' },
  { value: 'hsbc_smart', label: 'HSBC Smart Value Credit Card' },
  { value: 'hsbc_cashback', label: 'HSBC Cashback Credit Card' },
  { value: 'hsbc_platinum', label: 'HSBC Platinum Credit Card' }
] as const;